### PR TITLE
Add auto-build workflow and repo source label

### LINKED ISSUE #54: Add auto-build workflow
Add GitHub Actions workflow to auto-build and push `pipeval` image to `ghcr.io/uclahs-cds` registry on push to `main` or new release with `'v*'`-formatted tag.
Using template workflow: https://github.com/uclahs-cds/template-docker/blob/main/.github/workflows/Docker-build-release.yaml

### PR DESCRIPTION
**Pull request by aybeshlikyan**
### Formatting

- [X] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [X] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].

- [X] I have set up or verified the branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

### File Updates

- [ ] I have ensured that the version number update follows the [versioning standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Docker+image+versioning+standardization).

- [ ] I have updated the version number/dependencies and added my name to the maintainer list in the `Dockerfile`.

- [ ] I have updated the version number/feature changes in the `README.md`.

- [ ] I have updated the version number and added my name to the contributors list in the `metadata.yaml`.

- [X] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [ ] I have drafted the new version release with any additions/changes and have linked the `CHANGELOG.md` in the release. 

### Docker Hub Auto Build Rules

- [ ] I have created automated build rules following [this page](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/How+to+set+up+automated+builds+for+Docker+Hub) and I have not manually pushed this Docker image to the `blcdsdockerregistry` on [Docker Hub](https://hub.docker.com).

## Description

Closes #54 and #55. Adds auto-build and push workflow to the package and tests the repo source label in the Dockerfile.

### CODE REVIEW

**Review by yashpatel6 — APPROVED** [review]
Looks good to me! Let's see how much of the linking the label automatically does

**Comment by yashpatel6** [comment]
Yes merging should automatically trigger the build and push to the `dev` tag

**Comment by aybeshlikyan** [comment]
@yashpatel6 it failed 🥲  - https://github.com/uclahs-cds/public-tool-PipeVal/actions/runs/3237273055/jobs/5304127869

"Error: An action could not be found at the URI 'https://api.github.com/repos/uclahs-cds/tool-Docker-action/tarball/360e05d431247a5622e96cdf81ac702391fde39d'"

**Comment by yashpatel6** [comment]
Ah this is because the action repo is internal so public repos can't access the action; we might have to update the action repo to be public in order to allow access. We can discuss making the actions repos (or at least a subset of them) public at the infra meeting 🤔

**Comment by aybeshlikyan** [comment]
Ahh I forgot - can I do something in the meantime like use the entire original workflow as the workflow in Pipeval or will that not work?

**Comment by yashpatel6** [comment]
You could copy the workflow steps over and it should work in the meantime; the `inputs` block from the action isn't needed since it's mainly for composite actions.

**Pull request merged**
