### PR TITLE
Update to bl-base:1.1.0 and add 'bldocker'

### PR DESCRIPTION
**Pull request by aybeshlikyan**
### Formatting

- [X] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).

- [X] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].

- [X] I have set up or verified the branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.

### File Updates

- [ ] I have ensured that the version number update follows the [versioning standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Docker+image+versioning+standardization).

- [ ] I have updated the version number/dependencies and added my name to the maintainer list in the `Dockerfile`.

- [ ] I have updated the version number/feature changes in the `README.md`.

- [X] I have updated the version number and added my name to the contributors list in the `metadata.yaml`.

- [X] I have added the changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

- [ ] I have drafted the new version release with any additions/changes and have linked the `CHANGELOG.md` in the release. 

### Docker Hub Auto Build Rules

- [ ] I have created automated build rules following [this page](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/How+to+set+up+automated+builds+for+Docker+Hub) and I have not manually pushed this Docker image to the `blcdsdockerregistry` on [Docker Hub](https://hub.docker.com).

### Docker Image Testing

- [X] I have tested the Docker image with the `docker run` command as described below.

#### Test the Docker image with at least one sample. Verify the new Docker image works using:

```docker run -u $(id -u):$(id -g) –w <working-directory> -v <directory-you-want-to-mount>:<how-you-want-to-mount-it-within-the-docker> --rm <docker-image-name> <command-to-the-docker-with-all-parameters>```

#### My command: 

```docker build -t test-pipeval . -f docker/Dockerfile```
```docker run -it --rm test-pipeval /bin/bash -c "samtools --version; vcftools --version; tabix --version; pip --version; whoami; groups;"```

#### Output: 
```
samtools 1.11
Using htslib 1.11
Copyright (C) 2020 Genome Research Ltd.
VCFtools (0.1.16)
tabix (htslib) 1.11
Copyright (C) 2020 Genome Research Ltd.
pip 22.0.4 from /usr/local/lib/python3.10/site-packages/pip (python 3.10)
bldocker
bldocker
```

## Description

Updates bl-base to 1.1.0 and replaces `conda` with `mamba`. Adds `bldocker` user and group.

### CODE REVIEW

**Comment by aybeshlikyan** [comment]
When I try to create a file inside the container to test that the functions still run normally, the shell gives a "Permission denied" error. I think it's because `USER bldocker` in the Dockerfile is called before the `/tool` directory is created, so the owner/group of that directory is `root`. Is this the behavior we want?

**Comment by aholmes** [comment]
> When I try to create a file inside the container to test if the functions still run normally, the kernel gives a "Permission denied" error. I think it's because `USER bldocker` in the Dockerfile is called before the `/tool` directory is created, so the owner/group of that directory is `root`. Is this the behavior we want?

I think we would want this behavior, yes, however it does break both `md5-gen` and `sha512-gen` as the user can no longer write to any path, at least on our systems.

For testing, I grabbed a small BAM file and ran the script:

```bash
$ docker run -v ~/test-BAM:/mnt -it tool-pipeval

bldocker@9281a1eed349:/tool$ python3 -m validate -t file-bam /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam

Ran command: samtools quickcheck /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam
Input: /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam is valid file-bam
```

I also put an MD5 file alongside the BAM to test the MD5 validation:

```bash
bldocker@9281a1eed349:/tool$ python3 -m validate -t file-input /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam

Ran command: samtools quickcheck /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam
Input: /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam is valid file-bam
```

And after intentionally corrupting the MD5 file:

```bash
bldocker@9281a1eed349:/tool$ python3 -m validate -t file-input /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam

Error: /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam File is corrupted, md5 checksum failed.
```

Finally, MD5 generation:

```bash
bldocker@9281a1eed349:/tool$ python3 -m validate -t md5-gen /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam
Error: /mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam [Errno 13] Permission denied: '/mnt/wgEncodeUwRepliSeqK562G1AlnRep1.bam.md5'
```


What additional testing would you like to complete within the container? I'm sure we can find a way to accomplish it.

**Comment by aybeshlikyan** [comment]
> `USER bldocker` in the Dockerfile is called before the `/tool` directory is created

I meant `USER bldocker` is called after* the `/tool` directory is created, so the owner of `/tool` ends up being root.

I tested running `md5-gen` and `sha512-gen` on files in external volumes; it worked and the generated outputs persisted. I believe Nextflow works by mounting external volumes to each process container, so it should work. I'll run the align-RNA pipeline with this version of PipeVal to make sure.

**Comment by aholmes** [comment]
> I tested running `md5-gen` and `sha512-gen` on files in external volumes; it worked and the generated outputs persisted. I believe Nextflow works by mounting external volumes to each process container, so it should work. I'll run the align-RNA pipeline with this version of PipeVal to make sure.

Yes, this should work with, e.g., `/scratch`, which might be sufficient for our needs. We're working toward locking down access to some mounts though. @tyamaguchi-ucla any concerns about, e.g., `/hot`?

**Comment by tyamaguchi-ucla** [comment]
> Yes, this should work with, e.g., `/scratch`, which might be sufficient for our needs. We're working toward locking down access to some mounts though. @tyamaguchi-ucla any concerns about, e.g., `/hot`?

Not really with this tool because checksums are tiny although the input files can be huge. It can still cause some network issues if we load up huge files in parallel using a specific VM though regardless of the mount. (So we don't want to run `md5sum` or `sha512sum` for huge files in parallel (e.g. not more than 5-10 jobs depending on the file size) especially on the headnode.)

**Comment by tyamaguchi-ucla** [comment]
> regardless of the mount

I meant this is for **writing** the checksum files.

**Review by aholmes — APPROVED** [review]
Talked with @tyamaguchi-ucla. I had forgotten we run the container as the user running the pipeline, and that this change is to prevent unintentionally running the container as root. Looks good!

**Review by tyamaguchi-ucla — APPROVED** [review]

**Pull request merged**
